--!strict

export type EnumType =
	"A Frontier Of Dragons"
	| "Abandoned Orchard"
	| "Ancient Forest"
	| "Blackrock Mountain"
	| "Blue Ogre Camp"
	| "Celestial Field"
	| "Celestial Peak"
	| "Clamstack Cave"
	| "Coral Bay"
	| "Farm Fortress"
	| "Frigid Waste (PvP)"
	| "Gnome Magic School"
	| "Great Pine Forest"
	| "Greenhorn Grove"
	| "Hoodlum Falls"
	| "Matumada"
	| "Otherworld Tower"
	| "Pebble Bay"
	| "Petrified Grassland"
	| "Pit Depths"
	| "Rabbit Hole"
	| "Rubble Spring"
	| "Starry Point"
	| "Strangeman's Domain"
	| "The Deep Forest"
	| "The Forgotten Lands"
	| "The Long Coast"
	| "The Maze Wood"
	| "The Pits"
	| "The Quiet Field"
	| "The Rolling Road"
	| "The Spider's Nest"
	| "The Town of Right and Wrong"
	| "Topple Hill"
	| "Topple Lake"
	| "Topple Town"
	| "Twinkling Meadow"
	| "Upper Island"

local Frontier = {
	["A Frontier Of Dragons"] = "A Frontier Of Dragons" :: "A Frontier Of Dragons",
	["Abandoned Orchard"] = "Abandoned Orchard" :: "Abandoned Orchard",
	["Ancient Forest"] = "Ancient Forest" :: "Ancient Forest",
	["Blackrock Mountain"] = "Blackrock Mountain" :: "Blackrock Mountain",
	["Blue Ogre Camp"] = "Blue Ogre Camp" :: "Blue Ogre Camp",
	["Celestial Field"] = "Celestial Field" :: "Celestial Field",
	["Celestial Peak"] = "Celestial Peak" :: "Celestial Peak",
	["Clamstack Cave"] = "Clamstack Cave" :: "Clamstack Cave",
	["Coral Bay"] = "Coral Bay" :: "Coral Bay",
	["Farm Fortress"] = "Farm Fortress" :: "Farm Fortress",
	["Frigid Waste (PvP)"] = "Frigid Waste (PvP)" :: "Frigid Waste (PvP)",
	["Gnome Magic School"] = "Gnome Magic School" :: "Gnome Magic School",
	["Great Pine Forest"] = "Great Pine Forest" :: "Great Pine Forest",
	["Greenhorn Grove"] = "Greenhorn Grove" :: "Greenhorn Grove",
	["Hoodlum Falls"] = "Hoodlum Falls" :: "Hoodlum Falls",
	["Matumada"] = "Matumada" :: "Matumada",
	["Otherworld Tower"] = "Otherworld Tower" :: "Otherworld Tower",
	["Pebble Bay"] = "Pebble Bay" :: "Pebble Bay",
	["Petrified Grassland"] = "Petrified Grassland" :: "Petrified Grassland",
	["Pit Depths"] = "Pit Depths" :: "Pit Depths",
	["Rabbit Hole"] = "Rabbit Hole" :: "Rabbit Hole",
	["Rubble Spring"] = "Rubble Spring" :: "Rubble Spring",
	["Starry Point"] = "Starry Point" :: "Starry Point",
	["Strangeman's Domain"] = "Strangeman's Domain" :: "Strangeman's Domain",
	["The Deep Forest"] = "The Deep Forest" :: "The Deep Forest",
	["The Forgotten Lands"] = "The Forgotten Lands" :: "The Forgotten Lands",
	["The Long Coast"] = "The Long Coast" :: "The Long Coast",
	["The Maze Wood"] = "The Maze Wood" :: "The Maze Wood",
	["The Pits"] = "The Pits" :: "The Pits",
	["The Quiet Field"] = "The Quiet Field" :: "The Quiet Field",
	["The Rolling Road"] = "The Rolling Road" :: "The Rolling Road",
	["The Spider's Nest"] = "The Spider's Nest" :: "The Spider's Nest",
	["The Town of Right and Wrong"] = "The Town of Right and Wrong" :: "The Town of Right and Wrong",
	["Topple Hill"] = "Topple Hill" :: "Topple Hill",
	["Topple Lake"] = "Topple Lake" :: "Topple Lake",
	["Topple Town"] = "Topple Town" :: "Topple Town",
	["Twinkling Meadow"] = "Twinkling Meadow" :: "Twinkling Meadow",
	["Upper Island"] = "Upper Island" :: "Upper Island",
}

return Frontier
